#!/usr/bin/env bash

VM_DIR=/d/coding-avenue/vagrant

if [ -z "$1" ] 
then 
	exit
fi

for vm in $VM_DIR/*; do
	
	if [ "$vm" == "$VM_DIR/$1" ]
	then
		continue
	fi

	cd $vm
	echo "$vm: vagrant halt"
	vagrant halt 2> /dev/null
done

echo "$VM_DIR/$1: vagrant up"
cd $VM_DIR/$1
vagrant up
vagrant ssh
